spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kaibee
    username: kaibee
    password: kaibee
management:
  tracing:
    sampling:
      probability: 1.0
server:
  error:
    include-stacktrace: never